"use client";
import Image from "next/image";
import Link from "next/link";
import {useCart} from "@/app/CartProvider";
import {products} from "@/lib/data";
import {parsePrice,shippingFor} from "@/lib/commerce";
import CryptoCheckout from "./CryptoCheckout";
const money=(v:number)=>`$${v.toFixed(2)}`;

export default function CheckoutClient(){
 const{items}=useCart();
 const lines=items.flatMap(i=>{const product=products.find(p=>p.slug===i.slug);return product?[{...i,product}]:[]});
 const subtotal=lines.reduce((s,l)=>s+parsePrice(l.product.price)*l.quantity,0), shipping=lines.length?shippingFor(subtotal):0,total=subtotal+shipping;
 if(!lines.length)return <div className="container"><div className="card mx-auto max-w-xl rounded-[2rem] p-8 text-center"><div className="eyebrow">Checkout</div><h1 className="mt-3 text-3xl font-semibold">Nothing to check out yet.</h1><p className="mt-3 text-[var(--muted)]">Your cart is empty — let’s fix that.</p><Link href="/#products" className="mt-6 inline-flex rounded-full bg-[var(--primary)] px-6 py-3 text-sm font-semibold text-white">Shop products</Link></div></div>;
 return <div className="container grid gap-8 lg:grid-cols-[1.05fr_.95fr]"><div className="card rounded-[2rem] p-6 md:p-8"><div className="eyebrow">Checkout</div><h1 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">Almost yours.</h1><p className="mt-3 text-[var(--muted)]">A few details, then Bitcoin does its thing.</p>
 <form id="checkout-form"><div className="mt-8"><h2 className="text-lg font-semibold">Contact</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm">First name<input required name="firstName" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" autoComplete="given-name"/></label><label className="text-sm">Last name<input required name="lastName" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" autoComplete="family-name"/></label><label className="text-sm md:col-span-2">Email<input required name="email" type="email" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" autoComplete="email"/></label><label className="text-sm md:col-span-2">Phone <span className="text-[var(--muted)]">(optional)</span><input name="phone" type="tel" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" autoComplete="tel"/></label></div></div>
 <div className="mt-8"><h2 className="text-lg font-semibold">Shipping</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm md:col-span-2">Address<input required name="address" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" autoComplete="street-address"/></label><label className="text-sm">City<input required name="city" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" autoComplete="address-level2"/></label><label className="text-sm">State<input required name="state" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" autoComplete="address-level1"/></label><label className="text-sm">ZIP<input required name="postalCode" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" autoComplete="postal-code"/></label><label className="text-sm">Country<input required name="country" className="mt-2 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none" defaultValue="United States" autoComplete="country-name"/></label></div></div></form>
 <div className="mt-8"><h2 className="text-lg font-semibold">Payment</h2><p className="mt-2 text-sm text-[var(--muted)]">Complete your order securely with Bitcoin.</p><div className="mt-4 max-w-xl"><CryptoCheckout items={items}/></div></div></div>
 <aside className="space-y-4 lg:sticky lg:top-28 lg:self-start"><div className="card rounded-[2rem] p-6"><div className="text-sm text-[var(--muted)]">Order summary</div><div className="mt-5 space-y-4">{lines.map(({product,quantity})=><div key={product.slug} className="flex items-center gap-3"><Image src={product.image} alt="" width={64} height={64} className="h-14 w-14 rounded-xl bg-[var(--surface-soft)] object-contain"/><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{product.name}</div><div className="text-xs text-[var(--muted)]">Qty {quantity}</div></div><div className="text-sm font-semibold">{money(parsePrice(product.price)*quantity)}</div></div>)}</div><div className="mt-6 space-y-3 border-t border-black/5 pt-5 text-sm"><div className="flex justify-between"><span className="text-[var(--muted)]">Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between"><span className="text-[var(--muted)]">Shipping</span><span>{shipping===0?"Free":money(shipping)}</span></div><div className="flex justify-between border-t border-black/5 pt-3 text-base font-semibold"><span>Total</span><span>{money(total)}</span></div></div></div><Link href="/cart" className="block text-center text-sm font-medium text-[var(--primary)]">← Edit cart</Link></aside></div>
}
