"use client";
import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,Copy,LoaderCircle,LockKeyhole,WalletCards} from "lucide-react";
import {useCart,CartItem} from "@/app/CartProvider";
type Props={items:CartItem[]};
type Payment={orderId:string;paymentId:string;status:string;payAddress?:string;payAmount?:number;payCurrency?:string;totalUsd:number;productName:string};
const terminal=new Set(["finished","failed","refunded","expired"]);
export default function CryptoCheckout({items}:Props){const{clearCart}=useCart();const[loading,setLoading]=useState(false),[error,setError]=useState(""),[payment,setPayment]=useState<Payment|null>(null),[copied,setCopied]=useState<"amount"|"address"|null>(null);
const statusLabel=useMemo(()=>{const s=payment?.status||"";if(s==="finished")return"Payment received";if(["confirmed","sending"].includes(s))return"Payment confirmed";if(s==="confirming")return"Payment detected — confirming";if(s==="partially_paid")return"Partial payment received";if(s==="expired")return"Payment expired";if(s==="failed")return"Payment failed";return"Waiting for Bitcoin payment"},[payment?.status]);
useEffect(()=>{if(payment?.status==="finished")clearCart()},[payment?.status]);
useEffect(()=>{if(!payment?.paymentId||terminal.has(payment.status))return;const timer=setInterval(async()=>{try{const r=await fetch(`/api/nowpayments/status/${encodeURIComponent(payment.paymentId)}`,{cache:"no-store"});if(!r.ok)return;const d=await r.json();setPayment(c=>c?{...c,status:d.status||c.status}:c)}catch{}},10000);return()=>clearInterval(timer)},[payment?.paymentId,payment?.status]);
async function copy(v:string,k:"amount"|"address"){await navigator.clipboard.writeText(v);setCopied(k);setTimeout(()=>setCopied(null),1500)}
async function start(){setError("");const form=document.querySelector<HTMLFormElement>("#checkout-form");if(!form||!form.reportValidity())return;const fd=new FormData(form);const customer={firstName:String(fd.get("firstName")||""),lastName:String(fd.get("lastName")||""),email:String(fd.get("email")||""),phone:String(fd.get("phone")||""),address:String(fd.get("address")||""),city:String(fd.get("city")||""),state:String(fd.get("state")||""),postalCode:String(fd.get("postalCode")||""),country:String(fd.get("country")||"")};setLoading(true);try{const r=await fetch("/api/checkout/crypto",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...customer,items})});const d=await r.json();if(!r.ok)throw new Error(d.error||"We couldn’t start your payment. Nothing has been charged.");setPayment(d)}catch(e){setError(e instanceof Error?e.message:"We couldn’t start your payment. Nothing has been charged. Please try again.")}finally{setLoading(false)}}
if(payment)return <div className="rounded-[1.5rem] border border-black/10 bg-white p-5"><div className="flex items-center gap-3">{payment.status==="finished"?<CheckCircle2 size={22} className="text-emerald-600"/>:<WalletCards size={22} className="text-[var(--primary)]"/>}<div><div className="font-semibold">{payment.status==="finished"?"Payment received 🎉":"Your Bitcoin payment is ready."}</div><div className="text-xs text-[var(--muted)]">{statusLabel}</div></div></div>{payment.status!=="finished"&&<div className="mt-5 space-y-4"><div className="rounded-2xl bg-[var(--surface-soft)] p-4"><div className="text-xs uppercase tracking-wide text-[var(--muted)]">Send exactly</div><div className="mt-1 break-all text-lg font-semibold">{payment.payAmount} {String(payment.payCurrency||"BTC").toUpperCase()}</div>{payment.payAmount!=null&&<button type="button" onClick={()=>copy(String(payment.payAmount),"amount")} className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-[var(--primary)]"><Copy size={13}/>{copied==="amount"?"Copied":"Copy amount"}</button>}</div><div className="rounded-2xl bg-[var(--surface-soft)] p-4"><div className="text-xs uppercase tracking-wide text-[var(--muted)]">Bitcoin address</div><div className="mt-1 break-all text-sm font-medium">{payment.payAddress}</div>{payment.payAddress&&<button type="button" onClick={()=>copy(payment.payAddress!,"address")} className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-[var(--primary)]"><Copy size={13}/>{copied==="address"?"Copied":"Copy address"}</button>}</div><p className="text-xs leading-relaxed text-[var(--muted)]">Send the exact BTC amount to the address above. We’ll update this page automatically once your payment is confirmed.</p></div>}{payment.status==="finished"&&<div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-900">Your order is confirmed. We’ll take it from here. Order #{payment.orderId.slice(0,8).toUpperCase()}.</div>}</div>;
return <div className="rounded-[1.5rem] border border-black/10 bg-white p-5"><div className="flex items-center gap-3"><WalletCards size={20} className="text-[var(--primary)]"/><div className="font-semibold">Bitcoin</div></div><p className="mt-2 text-sm text-[var(--muted)]">Pay securely with BTC.</p><button type="button" disabled={loading||!items.length} onClick={start} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full bg-[var(--primary)] px-5 py-3.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{loading&&<LoaderCircle size={16} className="animate-spin"/>}{loading?"Preparing payment…":"Pay with Bitcoin"}</button>{error&&<p className="mt-3 text-xs text-red-600">{error}</p>}<div className="mt-4 flex items-start gap-2 text-xs text-[var(--muted)]"><LockKeyhole size={14} className="mt-0.5 shrink-0"/><span>Secure Bitcoin payment powered by NOWPayments.</span></div></div>}
